src/pedidos/urls.py
from django.urls import path
from .views import dashboard_view, update_pedido_view

app_name = 'pedidos'

urlpatterns = [
    path('', dashboard_view, name='dashboard'),
    path('update-pedido=<int:pk>', update_pedido_view, name='update-pedido'),
]

src/simulador_pedidos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('pedidos.urls')),
    path('admin/', admin.site.urls),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/pedidos/models.py
from django.db import models
from django.core.validators import MinValueValidator

import decimal

#====================================================================================
#=================== Modelo de validação da Cliente Pedido ==========================
#====================================================================================
#cliente 	 = campo obriagatório, seleciona um objeto do tipo Cliente
#items 		 = permite a inclusão de múltiplos objetos do tipo Item. Campo obrigatório
#total_items = campo prenchido pré ao salvamento na lógica descrita em signals.py
class Cliente(models.Model):
	nome 	= models.CharField(max_length=200, null=True)

	def __str__(self):
		return self.nome

#====================================================================================
#=================== Modelo de validação da classe Produtos =========================
#====================================================================================
#
#
#

class Produto(models.Model):
	nome 			= models.CharField(max_length=200, null=True)
	preço_unitario	= models.DecimalField(decimal_places=2, validators=[MinValueValidator(0.01)], null=True, max_digits=100)
	multiplo 		= models.PositiveIntegerField(null=True, blank=True, validators=[MinValueValidator(1)])

	def __str__(self):
		return self.nome

#====================================================================================
#=================== Modelo de validação da classe Item =============================
#====================================================================================
#
#
#
#
class Item(models.Model):
	produto 		= models.ForeignKey(Produto, on_delete=models.CASCADE, null=True)
	quantidade		= models.PositiveIntegerField(null=True, validators=[MinValueValidator(1)])
	preço_item		= models.DecimalField(null=True, decimal_places=2, max_digits=100, validators=[MinValueValidator(0.01)], blank=True)
	rentabilidade 	= models.CharField(null=True, blank=True, max_length=200)

	#nominação string dos objetos
	def __str__(self):
		return f'{self.produto.nome} - R${self.preço_item} - {self.rentabilidade}'


#====================================================================================
#=================== Modelo de validação da classe Pedido ===========================
#====================================================================================
#cliente 	 = campo obriagatório, seleciona um objeto do tipo Cliente
#items 		 = permite a inclusão de múltiplos objetos do tipo Item. Campo obrigatório
#total_items = campo prenchido pré ao salvamento na lógica descrita em signals.py

class Pedido(models.Model):
	cliente 		= models.ForeignKey(Cliente, on_delete=models.CASCADE)
	items 			= models.ManyToManyField(Item)
	total_price		= models.DecimalField(decimal_places=2, null=True, max_digits=1000, blank=True)
	total_items		= models.PositiveIntegerField(null=True, blank=True)
	pedido_validado	= models.BooleanField(null=True, blank=False, default=False)

	#nominação string dos objetos 
	def __str__(self):
		return f'{self.cliente.nome} - R${self.total_price}'

src/pedidos/forms.py
from django import forms
from .models import Item, Pedido

class ItemModelForm(forms.ModelForm):
	class Meta:
		model 	= Item
		fields 	= [
			'produto',
			'quantidade',
			'preço_item',
			'rentabilidade',
		]

class PedidoModelForm(forms.ModelForm):
	class Meta:
		model 	= Pedido
		fields	= [
			'cliente',
			'items',
			'total_price',
		]

		labels = {
		'items': 'Itens do pedido',
		'total_price': 'Preço Total - Calculado Automaticamente',

		}

		widgets = {
		'total_price': forms.TextInput(attrs={'readonly': 'readonly'})
		}

src/pedidos/views.py
from django.shortcuts import render
from django.contrib import messages
from .models import Item, Cliente, Produto, Pedido
from .forms import ItemModelForm, PedidoModelForm

# Create your views here.
def dashboard_view(request):


	qs_pedidos 		= Pedido.objects.all()
	qs_items 		= Item.objects.all()

	template_name 	= 'dashboard.html'
	context 		= {
			'page_title': 'Home Page',

			#Contadores 
			'total_clientes': Cliente.objects.all().count(),
			'total_produtos': Produto.objects.all().count(),
			'total_itens'	: Item.objects.all().count(),
			'total_pedidos' : Pedido.objects.all().count(),

			#Querysets
			'queryset_pedidos': qs_pedidos,
			'queryset_items': qs_items,

	}
	return render(request, template_name, context)

def update_pedido_view(request, pk):

	pedido 			= Pedido.objects.get(pk=pk)
	form 			= PedidoModelForm(request.POST or None, instance=pedido)
	
	if request.method == 'POST':
		if form.is_valid():
			instance = form.save()
			if instance.pedido_validado == False:
				messages.warning(request, 'Itens com rentabilidade ruim não são aceitos no pedido. Tente novamente com um pedido válido.')
				form = PedidoModelForm(request.POST or None, instance=pedido)
			if instance.pedido_validado == True:
				messages.info(request, 'Atualizações Salvas')
				form.save()
				form = PedidoModelForm(request.POST or None, instance=pedido)

	template_name 	= 'update-pedido.html'
	context			= {	
		'page_title': 'Update pedido #'+ str(pk),
		'form'		: form, 

	}

	return render(request, template_name, context)

src/pedidos/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>{{page_title}}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    {% block content %}



    {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Custom JS !-->
    <script type="text/javascript" src={% static "main.js" %}></script>


  </body>
</html>

src/pedidos/templates/cards-contadores.html
<div class="row" style="padding-right: 1%; padding-left: 1%">
	<div class="col">
		<div class="card text-white bg-primary mb-4" style="max-width: 16rem; text-align: center; margin: 1%;">
  		<div class="card-header"> Total de Clientes</div>
		<div class="card-body">
			<h3 class="card-text">{{total_clientes}}</h3>
		</div>
	</div>
	</div>
	<div class="col">
		<div class="card text-white bg-secondary mb-4" style="max-width: 16rem; text-align: center; margin: 1%;">
	  		<div class="card-header"> Total de Produtos</div>
			<div class="card-body">
				<h3 class="card-text">{{total_produtos}}</h3>
			</div>
		</div>
	</div>
	<div class="col">
		<div class="card text-white bg-success mb-4" style="max-width: 16rem; text-align: center; margin: 1%;">
	  		<div class="card-header"> Total de Itens</div>
			<div class="card-body">
				<h3 class="card-text">{{total_itens}}</h3>
			</div>
		</div>
	</div>
	<div class="col">
		<div class="card bg-light mb-4" style="max-width: 16rem; text-align: center; margin: 1%;">
	  		<div class="card-header"> Total de Pedidos</div>
			<div class="card-body">
				<h3 class="card-text">{{total_pedidos}}</h3>
			</div>
		</div>
	</div>

src/pedidos/templates/dashboard.html
{% extends 'base.html' %}
{% block content %}
	<div class='card'>
		<div class="header">
			<h5 class="card card-header" style="text-align: center;"> Totais </h5>
		</div>
		<div class="card card-body">
			{% include 'cards-contadores.html' %}
		</div>
	</div>
	<br>
	
	<div class="row">
		<div class="col-6">
			<div class="card">
				<div class="header">
					<h5 class="card card-header" style="text-align: center;"> Pedidos </h5>
				</div>
				<div class="card card-body">
					<table class="table table-responsive-md">
						<tr>
							<th>#</th>
							<th>Cliente</th>
							<th>Preço Total</th>
							<th>Nº. Itens</th>
							<th>Atualizar</th>
							<th>Deletar</th>
						</tr>
						<tr>
						{% for pedido in queryset_pedidos %}
							<td>{{pedido.pk}}</td>
							<td>{{pedido.cliente}}</td>
							<td>R$ {{pedido.total_price}}</td>
							<td>{{pedido.total_items}}</td>
							<td><a class="btn btn-outline-primary btn-sm btn btn-block" href="{% url 'pedidos:update-pedido' pk=pedido.pk %}">Atualizar</a></td>
 							<td>
 								<a class="btn btn-outline-danger btn-sm btn btn-block">Deletar</button></a>
 							</td>

 						{% endfor %}
 						</tr>
 					</table>
				</div>
			</div>
		</div>
		<div class="col-6">
			<div class="card">
				<div class="header">
					<h5 class="card card-header" style="text-align: center;"> Itens </h5>
				</div>
				<div class="card card-body">
					<table class="table table-responsive-md">
						<tr>
							<th>#</th>
							<th>Produto</th>
							<th>Qtd.</th>
							<th>Preço</th>
							<th>Rentável</th>
							<th>Atualizar</th>
							<th>Deletar</th>

						</tr>
						{% for item in queryset_items %}
						<tr>
							<td>{{item.pk}}</td>
							<td>{{item.produto}}</td>
							<td>{{item.quantidade}}</td>
							<td>R${{item.preço_item}}</td>
							<td>{{item.rentabilidade}}</td>
							<td><a class="btn btn-outline-primary btn-sm btn btn-block" data-bs-toggle="modal" data-bs-target="#itens-modal">Atualizar</a></td>
 							<td><a class="btn btn-outline-danger btn-sm btn btn-block" data-bs-toggle="modal" data-bs-target="#delete-item">Apagar</a></td>
 						</tr>
 						{% endfor %}
 					</table>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

src/pedidos/templates/lista-pedidos.html
{% extends 'base.html' %}

{% block content %}
<h1> Olá Mundo </h1>
{% endblock content %}

src/pedidos/templates/navbar.html
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="{% url 'pedidos:dashboard' %}">Lorena's API</a>
  </nav>
  <br>
  <br>
  <br>

src/pedidos/templates/update-pedido.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
		{% if messages %}
			{% for message in messages %}
	   			<div class="alert alert-{{message.tags}}" role="alert">
 					{{message}}
				</div>	   			 	
			{% endfor %}

		{% endif %}
	<br>
	<br>
	<br>
	<div class="card" >
		<div class="header">
			<h5 class="card card-header" style="text-align: center;"> Atualizar pedido </h5>
		</div>
		<div class="card card-body" style="padding: 2%">	
			<form method="POST">
			{% csrf_token %}
			{{form|crispy}}
			<br>
			<a href="{% url 'pedidos:dashboard' %}" class="btn btn-secondary">
				Cancelar</a>
			<button type="submit" class="btn btn-primary"> Atualizar </button>
		</form>
		</div>
	</div>
</div>

{% endblock content %}